import { useState, useEffect } from "react";

const I18N = {
  en: { appName:"FinAccess AI", switchToBank:"Bank View", switchToUser:"User View", role_user:"Customer", role_bank:"Bank Officer", tabs:{dashboard:"Dashboard",credit:"Credit Engine",risk:"Risk Forecast",products:"Products",rl:"RL Agent",finn:"FINNs"}, bankTabs:{overview:"Overview",applicants:"Applicants",portfolio:"Portfolio",fairness:"Fairness Audit",workflow:"Approvals"}, creditScore:"Credit Score", monthlyIncome:"Monthly Income", monthlyExpenses:"Monthly Expenses", financialRisk:"Financial Risk", repaymentHistory:"Repayment History (12 months)", liveSimulation:"Live Simulation — Adjust Parameters", aiAdvisor:"AI Financial Advisor", volatility:"Volatility", expenseRatio:"Expense ratio", shapTitle:"XGBoost Credit Score — Feature Impact (SHAP)", hurts:"← Hurts score", helps:"Helps score →", fairnessTitle:"Algorithmic Fairness (Fairlearn)", dataInputs:"Data Inputs", riskTrend:"12-Month Risk Trend (LSTM)", riskDrivers:"Risk Drivers Identified", nextMonth:"Next Month Prediction", distressProb:"Probability of financial distress", getActionPlan:"Get AI Action Plan ↗", products_title:"Matched Products", eligibility:"Eligibility match", explainElig:"Explain eligibility ↗", rlTitle:"RL Agent — Repayment Learning History", stateSpace:"State Space", rewardFn:"Reward Function", finnsTitle:"Finance-Informed Neural Network Constraints", finnVsML:"FINNs vs Classical ML", lossComponents:"Loss Function Components", explainFinn:"Explain FINNs concept ↗", live:"Live", aiQuestions:["What should I do to improve my credit score?","Am I at risk of financial distress?","Which loan product suits me best?"], totalApplicants:"Total Applicants", activeLoans:"Active Loans", avgScore:"Avg Credit Score", portfolioRisk:"Portfolio Risk", approveBtn:"Approve", flagBtn:"Flag", rejectBtn:"Reject", applicantList:"Applicant Queue", batchUpload:"Batch Score Upload", fairnessAudit:"Bias Detection Across Groups", approvalWorkflow:"Approval Workflow" },
  hi: { appName:"फिनएक्सेस AI", switchToBank:"बैंक दृश्य", switchToUser:"उपयोगकर्ता दृश्य", role_user:"ग्राहक", role_bank:"बैंक अधिकारी", tabs:{dashboard:"डैशबोर्ड",credit:"क्रेडिट इंजन",risk:"जोखिम पूर्वानुमान",products:"उत्पाद",rl:"RL एजेंट",finn:"FINNs"}, bankTabs:{overview:"अवलोकन",applicants:"आवेदक",portfolio:"पोर्टफोलियो",fairness:"निष्पक्षता जांच",workflow:"अनुमोदन"}, creditScore:"क्रेडिट स्कोर", monthlyIncome:"मासिक आय", monthlyExpenses:"मासिक खर्च", financialRisk:"वित्तीय जोखिम", repaymentHistory:"पुनर्भुगतान इतिहास (12 महीने)", liveSimulation:"लाइव सिमुलेशन — पैरामीटर बदलें", aiAdvisor:"AI वित्तीय सलाहकार", volatility:"अस्थिरता", expenseRatio:"खर्च अनुपात", shapTitle:"XGBoost क्रेडिट स्कोर — फीचर प्रभाव (SHAP)", hurts:"← स्कोर घटाता है", helps:"स्कोर बढ़ाता है →", fairnessTitle:"एल्गोरिदमिक निष्पक्षता", dataInputs:"डेटा इनपुट", riskTrend:"12-महीने जोखिम प्रवृत्ति", riskDrivers:"जोखिम कारण", nextMonth:"अगले महीने की भविष्यवाणी", distressProb:"वित्तीय संकट की संभावना", getActionPlan:"AI कार्य योजना प्राप्त करें ↗", products_title:"मिलान उत्पाद", eligibility:"पात्रता मिलान", explainElig:"पात्रता समझाएं ↗", rlTitle:"RL एजेंट — पुनर्भुगतान सीखने का इतिहास", stateSpace:"स्थिति स्थान", rewardFn:"पुरस्कार फ़ंक्शन", finnsTitle:"वित्त-सूचित न्यूरल नेटवर्क बाधाएं", finnVsML:"FINNs बनाम पारंपरिक ML", lossComponents:"लॉस फ़ंक्शन घटक", explainFinn:"FINNs अवधारणा समझाएं ↗", live:"लाइव", aiQuestions:["मेरा क्रेडिट स्कोर सुधारने के लिए मुझे क्या करना चाहिए?","क्या मुझे वित्तीय संकट का खतरा है?","मेरे लिए कौन सा लोन उत्पाद सबसे उपयुक्त है?"], totalApplicants:"कुल आवेदक", activeLoans:"सक्रिय ऋण", avgScore:"औसत क्रेडिट स्कोर", portfolioRisk:"पोर्टफोलियो जोखिम", approveBtn:"स्वीकृत", flagBtn:"चिह्नित", rejectBtn:"अस्वीकृत", applicantList:"आवेदक कतार", batchUpload:"बैच स्कोर अपलोड", fairnessAudit:"समूहों में पूर्वाग्रह पहचान", approvalWorkflow:"अनुमोदन वर्कफ़्लो" },
  ta: { appName:"ஃபின்அக்சஸ் AI", switchToBank:"வங்கி பார்வை", switchToUser:"பயனர் பார்வை", role_user:"வாடிக்கையாளர்", role_bank:"வங்கி அதிகாரி", tabs:{dashboard:"டாஷ்போர்டு",credit:"கடன் இயந்திரம்",risk:"இடர் முன்னறிவிப்பு",products:"தயாரிப்புகள்",rl:"RL முகவர்",finn:"FINNs"}, bankTabs:{overview:"கண்ணோட்டம்",applicants:"விண்ணப்பதாரர்கள்",portfolio:"போர்ட்ஃபோலியோ",fairness:"நியாயத்தன்மை தணிக்கை",workflow:"அனுமதிகள்"}, creditScore:"கடன் மதிப்பெண்", monthlyIncome:"மாத வருமானம்", monthlyExpenses:"மாத செலவுகள்", financialRisk:"நிதி இடர்", repaymentHistory:"திருப்பிச் செலுத்தல் வரலாறு (12 மாதங்கள்)", liveSimulation:"நேரடி உருவகப்படுத்துதல்", aiAdvisor:"AI நிதி ஆலோசகர்", volatility:"ஏற்ற இறக்கம்", expenseRatio:"செலவு விகிதம்", shapTitle:"XGBoost கடன் மதிப்பெண் — அம்சம் தாக்கம் (SHAP)", hurts:"← மதிப்பெண்ணை குறைக்கிறது", helps:"மதிப்பெண்ணை அதிகரிக்கிறது →", fairnessTitle:"அல்காரிதமிக் நியாயத்தன்மை", dataInputs:"தரவு உள்ளீடுகள்", riskTrend:"12 மாத இடர் போக்கு", riskDrivers:"இடர் காரணிகள்", nextMonth:"அடுத்த மாத முன்னறிவிப்பு", distressProb:"நிதி நெருக்கடி நிகழ்தகவு", getActionPlan:"AI செயல் திட்டம் பெறுக ↗", products_title:"பொருந்திய தயாரிப்புகள்", eligibility:"தகுதி பொருத்தம்", explainElig:"தகுதி விளக்கம் ↗", rlTitle:"RL முகவர் — திருப்பிச் செலுத்தல் கற்றல் வரலாறு", stateSpace:"நிலை இடம்", rewardFn:"வெகுமதி செயல்பாடு", finnsTitle:"நிதி-தகவல் நரம்பியல் வலைப்பின்னல் தடைகள்", finnVsML:"FINNs மற்றும் வழக்கமான ML", lossComponents:"இழப்பு செயல்பாடு கூறுகள்", explainFinn:"FINNs கருத்தை விளக்கு ↗", live:"நேரடி", aiQuestions:["என் கடன் மதிப்பெண்ணை மேம்படுத்த என்ன செய்ய வேண்டும்?","என்னிடம் நிதி நெருக்கடி அபாயம் உள்ளதா?","எனக்கு எந்த கடன் தயாரிப்பு சிறந்தது?"], totalApplicants:"மொத்த விண்ணப்பதாரர்கள்", activeLoans:"செயல்படும் கடன்கள்", avgScore:"சராசரி கடன் மதிப்பெண்", portfolioRisk:"போர்ட்ஃபோலியோ இடர்", approveBtn:"அனுமதி", flagBtn:"கொடியிடு", rejectBtn:"நிராகரி", applicantList:"விண்ணப்பதாரர் வரிசை", batchUpload:"தொகுதி மதிப்பெண் பதிவேற்றம்", fairnessAudit:"குழுக்களில் சார்பு கண்டறிதல்", approvalWorkflow:"அனுமதி பணிப்பாய்வு" },
  te: { appName:"ఫిన్‌యాక్సెస్ AI", switchToBank:"బ్యాంక్ వ్యూ", switchToUser:"వినియోగదారు వ్యూ", role_user:"వినియోగదారు", role_bank:"బ్యాంక్ అధికారి", tabs:{dashboard:"డ్యాష్‌బోర్డ్",credit:"క్రెడిట్ ఇంజిన్",risk:"రిస్క్ అంచనా",products:"ఉత్పత్తులు",rl:"RL ఏజెంట్",finn:"FINNs"}, bankTabs:{overview:"అవలోకనం",applicants:"దరఖాస్తుదారులు",portfolio:"పోర్ట్‌ఫోలియో",fairness:"న్యాయ తనిఖీ",workflow:"ఆమోదాలు"}, creditScore:"క్రెడిట్ స్కోర్", monthlyIncome:"నెలవారీ ఆదాయం", monthlyExpenses:"నెలవారీ ఖర్చులు", financialRisk:"ఆర్థిక ప్రమాదం", repaymentHistory:"తిరిగి చెల్లింపు చరిత్ర (12 నెలలు)", liveSimulation:"లైవ్ సిమ్యులేషన్", aiAdvisor:"AI ఆర్థిక సలహాదారు", volatility:"అస్థిరత", expenseRatio:"వ్యయ నిష్పత్తి", shapTitle:"XGBoost క్రెడిట్ స్కోర్ — ఫీచర్ ప్రభావం (SHAP)", hurts:"← స్కోర్ తగ్గిస్తుంది", helps:"స్కోర్ పెంచుతుంది →", fairnessTitle:"అల్గోరిథమిక్ న్యాయం", dataInputs:"డేటా ఇన్‌పుట్‌లు", riskTrend:"12-నెలల రిస్క్ ట్రెండ్", riskDrivers:"రిస్క్ కారణాలు", nextMonth:"తదుపరి నెల అంచనా", distressProb:"ఆర్థిక సంక్షోభ సంభావ్యత", getActionPlan:"AI చర్య ప్రణాళిక ↗", products_title:"సరిపోలిన ఉత్పత్తులు", eligibility:"అర్హత సరిపోలిక", explainElig:"అర్హత వివరించు ↗", rlTitle:"RL ఏజెంట్ — తిరిగి చెల్లింపు అభ్యాస చరిత్ర", stateSpace:"స్టేట్ స్పేస్", rewardFn:"రివార్డ్ ఫంక్షన్", finnsTitle:"ఫైనాన్స్-ఇన్ఫార్మ్డ్ న్యూరల్ నెట్‌వర్క్ పరిమితులు", finnVsML:"FINNs vs సాంప్రదాయ ML", lossComponents:"లాస్ ఫంక్షన్ భాగాలు", explainFinn:"FINNs భావన వివరించు ↗", live:"లైవ్", aiQuestions:["నా క్రెడిట్ స్కోర్ మెరుగుపరచడానికి ఏమి చేయాలి?","నాకు ఆర్థిక సంక్షోభం ప్రమాదం ఉందా?","నాకు ఏ రుణ ఉత్పత్తి అనుకూలమైనది?"], totalApplicants:"మొత్తం దరఖాస్తుదారులు", activeLoans:"క్రియాశీల రుణాలు", avgScore:"సగటు క్రెడిట్ స్కోర్", portfolioRisk:"పోర్ట్‌ఫోలియో రిస్క్", approveBtn:"ఆమోదించు", flagBtn:"ఫ్లాగ్", rejectBtn:"తిరస్కరించు", applicantList:"దరఖాస్తుదారుల క్యూ", batchUpload:"బ్యాచ్ స్కోర్ అప్‌లోడ్", fairnessAudit:"గ్రూపులలో పక్షపాత గుర్తింపు", approvalWorkflow:"ఆమోద వర్క్‌ఫ్లో" },
  bn: { appName:"ফিনঅ্যাক্সেস AI", switchToBank:"ব্যাংক ভিউ", switchToUser:"ব্যবহারকারী ভিউ", role_user:"গ্রাহক", role_bank:"ব্যাংক কর্মকর্তা", tabs:{dashboard:"ড্যাশবোর্ড",credit:"ক্রেডিট ইঞ্জিন",risk:"ঝুঁকি পূর্বাভাস",products:"পণ্য",rl:"RL এজেন্ট",finn:"FINNs"}, bankTabs:{overview:"সংক্ষিপ্ত বিবরণ",applicants:"আবেদনকারীরা",portfolio:"পোর্টফোলিও",fairness:"ন্যায়বিচার নিরীক্ষা",workflow:"অনুমোদন"}, creditScore:"ক্রেডিট স্কোর", monthlyIncome:"মাসিক আয়", monthlyExpenses:"মাসিক ব্যয়", financialRisk:"আর্থিক ঝুঁকি", repaymentHistory:"পরিশোধের ইতিহাস (১২ মাস)", liveSimulation:"লাইভ সিমুলেশন", aiAdvisor:"AI আর্থিক উপদেষ্টা", volatility:"অস্থিরতা", expenseRatio:"ব্যয় অনুপাত", shapTitle:"XGBoost ক্রেডিট স্কোর — বৈশিষ্ট্য প্রভাব (SHAP)", hurts:"← স্কোর কমায়", helps:"স্কোর বাড়ায় →", fairnessTitle:"অ্যালগরিদমিক ন্যায়বিচার", dataInputs:"ডেটা ইনপুট", riskTrend:"১২ মাসের ঝুঁকির প্রবণতা", riskDrivers:"ঝুঁকির কারণ", nextMonth:"পরের মাসের পূর্বাভাস", distressProb:"আর্থিক সংকটের সম্ভাবনা", getActionPlan:"AI কর্মপরিকল্পনা পান ↗", products_title:"মিলে যাওয়া পণ্য", eligibility:"যোগ্যতা মিল", explainElig:"যোগ্যতা ব্যাখ্যা করুন ↗", rlTitle:"RL এজেন্ট — পরিশোধ শেখার ইতিহাস", stateSpace:"স্টেট স্পেস", rewardFn:"রিওয়ার্ড ফাংশন", finnsTitle:"ফিনান্স-ইনফর্মড নিউরাল নেটওয়ার্ক সীমাবদ্ধতা", finnVsML:"FINNs বনাম ক্লাসিক্যাল ML", lossComponents:"লস ফাংশন উপাদান", explainFinn:"FINNs ধারণা ব্যাখ্যা করুন ↗", live:"লাইভ", aiQuestions:["আমার ক্রেডিট স্কোর উন্নত করতে কী করা উচিত?","আমি কি আর্থিক সংকটের ঝুঁকিতে আছি?","আমার জন্য কোন ঋণ পণ্যটি সবচেয়ে উপযুক্ত?"], totalApplicants:"মোট আবেদনকারী", activeLoans:"সক্রিয় ঋণ", avgScore:"গড় ক্রেডিট স্কোর", portfolioRisk:"পোর্টফোলিও ঝুঁকি", approveBtn:"অনুমোদন", flagBtn:"ফ্ল্যাগ", rejectBtn:"প্রত্যাখ্যান", applicantList:"আবেদনকারীর সারি", batchUpload:"ব্যাচ স্কোর আপলোড", fairnessAudit:"গোষ্ঠীগুলিতে পক্ষপাত সনাক্তকরণ", approvalWorkflow:"অনুমোদন ওয়ার্কফ্লো" },
  kn: { appName:"ಫಿನ್‌ಆಕ್ಸೆಸ್ AI", switchToBank:"ಬ್ಯಾಂಕ್ ವ್ಯೂ", switchToUser:"ಬಳಕೆದಾರ ವ್ಯೂ", role_user:"ಗ್ರಾಹಕ", role_bank:"ಬ್ಯಾಂಕ್ ಅಧಿಕಾರಿ", tabs:{dashboard:"ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",credit:"ಕ್ರೆಡಿಟ್ ಎಂಜಿನ್",risk:"ರಿಸ್ಕ್ ಮುನ್ಸೂಚನೆ",products:"ಉತ್ಪನ್ನಗಳು",rl:"RL ಏಜೆಂಟ್",finn:"FINNs"}, bankTabs:{overview:"ಅವಲೋಕನ",applicants:"ಅರ್ಜಿದಾರರು",portfolio:"ಪೋರ್ಟ್‌ಫೋಲಿಯೋ",fairness:"ನ್ಯಾಯ ಲೆಕ್ಕಪರಿಶೋಧನೆ",workflow:"ಅನುಮೋದನೆಗಳು"}, creditScore:"ಕ್ರೆಡಿಟ್ ಸ್ಕೋರ್", monthlyIncome:"ಮಾಸಿಕ ಆದಾಯ", monthlyExpenses:"ಮಾಸಿಕ ವೆಚ್ಚ", financialRisk:"ಆರ್ಥಿಕ ಅಪಾಯ", repaymentHistory:"ಮರುಪಾವತಿ ಇತಿಹಾಸ (12 ತಿಂಗಳು)", liveSimulation:"ಲೈವ್ ಸಿಮ್ಯುಲೇಶನ್", aiAdvisor:"AI ಆರ್ಥಿಕ ಸಲಹೆಗಾರ", volatility:"ಚಂಚಲತೆ", expenseRatio:"ವೆಚ್ಚ ಅನುಪಾತ", shapTitle:"XGBoost ಕ್ರೆಡಿಟ್ ಸ್ಕೋರ್ — ವೈಶಿಷ್ಟ್ಯ ಪ್ರಭಾವ (SHAP)", hurts:"← ಸ್ಕೋರ್ ಕಡಿಮೆ ಮಾಡುತ್ತದೆ", helps:"ಸ್ಕೋರ್ ಹೆಚ್ಚಿಸುತ್ತದೆ →", fairnessTitle:"ಅಲ್ಗೋರಿದಮಿಕ್ ನ್ಯಾಯ", dataInputs:"ಡೇಟಾ ಇನ್‌ಪುಟ್‌ಗಳು", riskTrend:"12-ತಿಂಗಳ ರಿಸ್ಕ್ ಟ್ರೆಂಡ್", riskDrivers:"ರಿಸ್ಕ್ ಕಾರಣಗಳು", nextMonth:"ಮುಂದಿನ ತಿಂಗಳ ಮುನ್ಸೂಚನೆ", distressProb:"ಆರ್ಥಿಕ ಸಂಕಟದ ಸಂಭಾವ್ಯತೆ", getActionPlan:"AI ಕ್ರಿಯಾ ಯೋಜನೆ ↗", products_title:"ಹೊಂದಿಸಿದ ಉತ್ಪನ್ನಗಳು", eligibility:"ಅರ್ಹತೆ ಹೊಂದಾಣಿಕೆ", explainElig:"ಅರ್ಹತೆ ವಿವರಿಸಿ ↗", rlTitle:"RL ಏಜೆಂಟ್ — ಮರುಪಾವತಿ ಕಲಿಕೆ ಇತಿಹಾಸ", stateSpace:"ಸ್ಟೇಟ್ ಸ್ಪೇಸ್", rewardFn:"ರಿವಾರ್ಡ್ ಫಂಕ್ಷನ್", finnsTitle:"ಹಣಕಾಸು-ತಿಳಿಸಿದ ನ್ಯೂರಲ್ ನೆಟ್‌ವರ್ಕ್ ನಿರ್ಬಂಧಗಳು", finnVsML:"FINNs ವಿರುದ್ಧ ಸಾಂಪ್ರದಾಯಿಕ ML", lossComponents:"ಲಾಸ್ ಫಂಕ್ಷನ್ ಘಟಕಗಳು", explainFinn:"FINNs ಪರಿಕಲ್ಪನೆ ವಿವರಿಸಿ ↗", live:"ಲೈವ್", aiQuestions:["ನನ್ನ ಕ್ರೆಡಿಟ್ ಸ್ಕೋರ್ ಸುಧಾರಿಸಲು ಏನು ಮಾಡಬೇಕು?","ನನಗೆ ಆರ್ಥಿಕ ಸಂಕಟದ ಅಪಾಯ ಇದೆಯೇ?","ನನಗೆ ಯಾವ ಸಾಲ ಉತ್ಪನ್ನ ಸೂಕ್ತ?"], totalApplicants:"ಒಟ್ಟು ಅರ್ಜಿದಾರರು", activeLoans:"ಸಕ್ರಿಯ ಸಾಲಗಳು", avgScore:"ಸರಾಸರಿ ಕ್ರೆಡಿಟ್ ಸ್ಕೋರ್", portfolioRisk:"ಪೋರ್ಟ್‌ಫೋಲಿಯೋ ರಿಸ್ಕ್", approveBtn:"ಅನುಮೋದಿಸಿ", flagBtn:"ಫ್ಲ್ಯಾಗ್", rejectBtn:"ತಿರಸ್ಕರಿಸಿ", applicantList:"ಅರ್ಜಿದಾರರ ಸರದಿ", batchUpload:"ಬ್ಯಾಚ್ ಸ್ಕೋರ್ ಅಪ್‌ಲೋಡ್", fairnessAudit:"ಗುಂಪುಗಳಲ್ಲಿ ಪಕ್ಷಪಾತ ಪತ್ತೆ", approvalWorkflow:"ಅನುಮೋದನ ವರ್ಕ್‌ಫ್ಲೋ" },
  mr: { appName:"फिनअॅक्सेस AI", switchToBank:"बँक दृश्य", switchToUser:"वापरकर्ता दृश्य", role_user:"ग्राहक", role_bank:"बँक अधिकारी", tabs:{dashboard:"डॅशबोर्ड",credit:"क्रेडिट इंजिन",risk:"जोखीम अंदाज",products:"उत्पादने",rl:"RL एजंट",finn:"FINNs"}, bankTabs:{overview:"आढावा",applicants:"अर्जदार",portfolio:"पोर्टफोलिओ",fairness:"निष्पक्षता लेखापरीक्षण",workflow:"मंजुरी"}, creditScore:"क्रेडिट स्कोअर", monthlyIncome:"मासिक उत्पन्न", monthlyExpenses:"मासिक खर्च", financialRisk:"आर्थिक जोखीम", repaymentHistory:"परतफेड इतिहास (12 महिने)", liveSimulation:"लाइव्ह सिम्युलेशन", aiAdvisor:"AI आर्थिक सल्लागार", volatility:"अस्थिरता", expenseRatio:"खर्च गुणोत्तर", shapTitle:"XGBoost क्रेडिट स्कोअर — वैशिष्ट्य प्रभाव (SHAP)", hurts:"← स्कोअर कमी करते", helps:"स्कोअर वाढवते →", fairnessTitle:"अल्गोरिदमिक निष्पक्षता", dataInputs:"डेटा इनपुट", riskTrend:"12-महिने जोखीम ट्रेंड", riskDrivers:"जोखीम कारणे", nextMonth:"पुढील महिन्याचा अंदाज", distressProb:"आर्थिक संकटाची शक्यता", getActionPlan:"AI कृती योजना मिळवा ↗", products_title:"जुळलेली उत्पादने", eligibility:"पात्रता जुळणी", explainElig:"पात्रता समजावा ↗", rlTitle:"RL एजंट — परतफेड शिकण्याचा इतिहास", stateSpace:"स्टेट स्पेस", rewardFn:"रिवॉर्ड फंक्शन", finnsTitle:"वित्त-माहिती तंत्रिका नेटवर्क बंधने", finnVsML:"FINNs विरुद्ध पारंपरिक ML", lossComponents:"लॉस फंक्शन घटक", explainFinn:"FINNs संकल्पना समजावा ↗", live:"लाइव्ह", aiQuestions:["माझा क्रेडिट स्कोअर सुधारण्यासाठी काय करावे?","मला आर्थिक संकटाचा धोका आहे का?","माझ्यासाठी कोणती कर्ज योजना योग्य आहे?"], totalApplicants:"एकूण अर्जदार", activeLoans:"सक्रिय कर्जे", avgScore:"सरासरी क्रेडिट स्कोअर", portfolioRisk:"पोर्टफोलिओ जोखीम", approveBtn:"मंजूर", flagBtn:"ध्वज", rejectBtn:"नाकारा", applicantList:"अर्जदार रांग", batchUpload:"बॅच स्कोअर अपलोड", fairnessAudit:"गटांमध्ये पूर्वग्रह शोध", approvalWorkflow:"मंजुरी वर्कफ्लो" },
};

const LANGS=[{code:"en",label:"EN",name:"English"},{code:"hi",label:"हि",name:"Hindi"},{code:"ta",label:"த",name:"Tamil"},{code:"te",label:"తె",name:"Telugu"},{code:"bn",label:"বা",name:"Bengali"},{code:"kn",label:"ಕ",name:"Kannada"},{code:"mr",label:"म",name:"Marathi"}];

const T={bg:"#07090f",card:"#0f1623",cardAlt:"#111c2e",border:"#1a2840",gold:"#d4a843",teal:"#00c9a7",red:"#f25a5a",blue:"#4fa3e0",purple:"#a78bfa",text:"#dde6f0",muted:"#5b7085",dim:"#1e2d42"};

const RISK_HISTORY=[{month:"Apr",risk:22,income:29000,expense:19000},{month:"May",risk:28,income:26000,expense:22000},{month:"Jun",risk:18,income:34000,expense:18500},{month:"Jul",risk:35,income:24000,expense:23000},{month:"Aug",risk:42,income:22000,expense:24000},{month:"Sep",risk:30,income:31000,expense:20000},{month:"Oct",risk:25,income:33000,expense:19500},{month:"Nov",risk:38,income:27000,expense:22000},{month:"Dec",risk:20,income:36000,expense:18000},{month:"Jan",risk:24,income:35000,expense:19000},{month:"Feb",risk:29,income:31000,expense:21000},{month:"Mar",risk:33,income:32000,expense:21000}];
const SHAP_FEATURES=[{name:"Income volatility",value:-0.18,impact:"negative"},{name:"Repayment consistency",value:+0.31,impact:"positive"},{name:"Savings rate",value:+0.14,impact:"positive"},{name:"Expense ratio",value:-0.09,impact:"negative"},{name:"Existing loans",value:-0.07,impact:"negative"},{name:"Income level",value:+0.12,impact:"positive"}];
const PRODUCTS=[{id:1,type:"Micro Loan",name:"PM SVANidhi",amount:"₹50,000",rate:"7%",term:"12 mo",eligibility:85,tag:"Govt. Backed",desc:"Street vendor & gig worker micro-credit",color:T.teal},{id:2,type:"Personal Loan",name:"Jan Samarth",amount:"₹1,50,000",rate:"10.5%",term:"24 mo",eligibility:72,tag:"Recommended",desc:"National credit guarantee scheme",color:T.blue},{id:3,type:"Insurance",name:"PM Jeevan Jyoti",amount:"₹2,00,000",rate:"₹436/yr",term:"Annual",eligibility:95,tag:"Best Match",desc:"Life insurance for informal sector",color:T.gold},{id:4,type:"Subsidy",name:"MUDRA Yojana",amount:"₹3,00,000",rate:"8.5%",term:"36 mo",eligibility:61,tag:"Requires Docs",desc:"Micro-unit development loan",color:T.red}];
const RL_EPS=[{ep:1,reward:-1,action:"Skipped",score:620},{ep:2,reward:-1,action:"Skipped",score:608},{ep:3,reward:1,action:"On-time",score:625},{ep:4,reward:1,action:"On-time",score:641},{ep:5,reward:1,action:"On-time",score:656},{ep:6,reward:0.5,action:"Partial",score:659},{ep:7,reward:1,action:"On-time",score:671},{ep:8,reward:1,action:"On-time",score:682}];
const FINN_C=[{rule:"Expenditure ≤ 90% of income",status:"pass",actual:"65.6%",threshold:"< 90%"},{rule:"Debt-to-income ratio ≤ 40%",status:"pass",actual:"18.2%",threshold:"< 40%"},{rule:"Minimum 3 months income saved",status:"warn",actual:"1.5 mo",threshold:"≥ 3 mo"},{rule:"Repayment rate ≥ 70%",status:"pass",actual:"75%",threshold:"≥ 70%"},{rule:"Zero income → zero credit",status:"pass",actual:"N/A",threshold:"Hard rule"},{rule:"No debt service if income = 0",status:"pass",actual:"N/A",threshold:"Hard rule"}];
const INIT_APPLICANTS=[{id:"AP001",name:"Priya Sharma",score:714,risk:18,income:45000,product:"Personal Loan",status:"pending",source:"Salaried"},{id:"AP002",name:"Raju Verma",score:589,risk:52,income:18000,product:"Micro Loan",status:"flagged",source:"Gig"},{id:"AP003",name:"Meena Devi",score:651,risk:33,income:27000,product:"MUDRA",status:"pending",source:"Self-employed"},{id:"AP004",name:"Karthik R.",score:731,risk:15,income:62000,product:"Personal Loan",status:"approved",source:"Salaried"},{id:"AP005",name:"Fatima B.",score:603,risk:44,income:22000,product:"Micro Loan",status:"pending",source:"Gig"},{id:"AP006",name:"Suresh P.",score:678,risk:27,income:38000,product:"MUDRA",status:"pending",source:"Business"}];

function SparkLine({data,color=T.teal,width=120,height=36}){
  const max=Math.max(...data),min=Math.min(...data),range=max-min||1;
  const pts=data.map((v,i)=>{const x=(i/(data.length-1))*(width-4)+2,y=height-4-((v-min)/range)*(height-8);return `${x},${y}`;}).join(" ");
  return <svg width={width} height={height} style={{display:"block"}}><polyline points={pts} fill="none" stroke={color} strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>{data.map((v,i)=>{const x=(i/(data.length-1))*(width-4)+2,y=height-4-((v-min)/range)*(height-8);return i===data.length-1?<circle key={i} cx={x} cy={y} r={3} fill={color}/>:null;})}</svg>;
}

function ScoreGauge({score}){
  const pct=(score-300)/600,angle=-140+pct*280,color=score<580?T.red:score<670?T.gold:T.teal,label=score<580?"Poor":score<670?"Fair":score<750?"Good":"Excellent";
  return <svg viewBox="0 0 200 120" width="100%" style={{maxWidth:220}}><path d="M 20 110 A 80 80 0 1 1 180 110" fill="none" stroke={T.border} strokeWidth="12" strokeLinecap="round"/><path d="M 20 110 A 80 80 0 1 1 180 110" fill="none" stroke={color} strokeWidth="12" strokeLinecap="round" strokeDasharray={`${pct*251} 251`}/><g transform={`rotate(${angle}, 100, 110)`}><line x1="100" y1="110" x2="100" y2="42" stroke={color} strokeWidth="2" strokeLinecap="round"/><circle cx="100" cy="110" r="5" fill={color}/></g><text x="100" y="95" textAnchor="middle" fill={color} style={{fontSize:28,fontWeight:700,fontFamily:"monospace"}}>{score}</text><text x="100" y="112" textAnchor="middle" fill={T.muted} style={{fontSize:11}}>{label}</text></svg>;
}

function ShapBar({feature,value,impact}){
  const color=impact==="positive"?T.teal:T.red,w=Math.abs(value)/0.35*140;
  return <div style={{display:"flex",alignItems:"center",gap:8,marginBottom:6}}><div style={{width:160,fontSize:11,color:T.muted,textAlign:"right",flexShrink:0}}>{feature}</div><div style={{width:140,height:14,display:"flex",alignItems:"center",justifyContent:impact==="positive"?"flex-start":"flex-end"}}><div style={{width:w,height:10,borderRadius:3,background:color,opacity:0.85}}/></div><div style={{fontSize:11,color,width:42}}>{value>0?"+":""}{value.toFixed(2)}</div></div>;
}

export default function App(){
  const [lang,setLang]=useState("en");
  const [role,setRole]=useState("user");
  const [tab,setTab]=useState("dashboard");
  const [bankTab,setBankTab]=useState("overview");
  const [income,setIncome]=useState(32000);
  const [expense,setExpense]=useState(21000);
  const [score,setScore]=useState(671);
  const [riskPct,setRiskPct]=useState(33);
  const [aiLoading,setAiLoading]=useState(false);
  const [aiResponse,setAiResponse]=useState("");
  const [applicants,setApplicants]=useState(INIT_APPLICANTS);
  const [showLang,setShowLang]=useState(false);
  const t=I18N[lang];

  useEffect(()=>{const r=expense/income;setScore(Math.max(300,Math.min(900,Math.round(750-r*200+(income/1000)*2))));setRiskPct(Math.round(r*60));},[income,expense]);
  useEffect(()=>{setTab("dashboard");setBankTab("overview");setAiResponse("");},[role]);

  async function askAI(prompt){
    setAiLoading(true);setAiResponse("");
    try{
      const res=await fetch("https://api.anthropic.com/v1/messages",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({model:"claude-sonnet-4-20250514",max_tokens:800,system:`You are a financial AI advisor for FinAccess, serving Indian users. Profile: Income ₹${income}/mo, Expenses ₹${expense}/mo, Credit score ${score}, Risk ${riskPct}%. Reply in ${LANGS.find(l=>l.code===lang)?.name||"English"}. Be concise (2-3 sentences).`,messages:[{role:"user",content:prompt}]})});
      const d=await res.json();setAiResponse(d.content?.map(c=>c.text||"").join("")||"Unable to respond.");
    }catch{setAiResponse("AI advisor temporarily unavailable.");}
    setAiLoading(false);
  }

  const card={background:T.card,border:`1px solid ${T.border}`,borderRadius:12,padding:18};
  const cardAlt={background:T.cardAlt,border:`1px solid ${T.border}`,borderRadius:12,padding:18};
  const label={fontSize:10,color:T.muted,textTransform:"uppercase",letterSpacing:1,marginBottom:4};
  const badge={fontSize:10,padding:"2px 7px",borderRadius:20,fontWeight:600};
  const navBtn=(a)=>({padding:"5px 12px",borderRadius:6,border:"none",background:a?(role==="bank"?T.blue:T.gold):"transparent",color:a?"#07090f":T.muted,fontSize:11,fontWeight:a?700:400,cursor:"pointer"});
  const g2={display:"grid",gridTemplateColumns:"1fr 1fr",gap:12};
  const sec={padding:"16px 20px",maxWidth:1100,margin:"0 auto"};

  const AIBox=({accentColor})=>(aiResponse||aiLoading)?<div style={{...cardAlt,marginTop:12,borderLeft:`3px solid ${accentColor}`}}>{aiLoading?<div style={{fontSize:12,color:accentColor}}>◌ Thinking…</div>:<div style={{fontSize:13,lineHeight:1.7}}>{aiResponse}</div>}</div>:null;

  // ── USER TABS ─────────────────────────────────────────────────────────────
  const Dashboard=()=>(
    <div style={sec}>
      <div style={{display:"grid",gridTemplateColumns:"auto 1fr 1fr 1fr",gap:12,marginBottom:12}}>
        <div style={{...card,display:"flex",flexDirection:"column",alignItems:"center",padding:"14px 20px"}}><div style={label}>{t.creditScore}</div><ScoreGauge score={score}/></div>
        {[[t.monthlyIncome,`₹${(income/1000).toFixed(0)}k`,T.teal,RISK_HISTORY.map(d=>d.income/1000)],[t.monthlyExpenses,`₹${(expense/1000).toFixed(0)}k`,T.gold,RISK_HISTORY.map(d=>d.expense/1000)],[t.financialRisk,`${riskPct}%`,riskPct>40?T.red:T.teal,RISK_HISTORY.map(d=>d.risk)]].map(([lbl,val,col,data])=>(
          <div key={lbl} style={card}><div style={label}>{lbl}</div><div style={{fontSize:20,fontWeight:700,fontFamily:"monospace",color:col}}>{val}</div><div style={{marginTop:8}}><SparkLine data={data} color={col}/></div></div>
        ))}
      </div>
      <div style={{...card,marginBottom:12}}>
        <div style={label}>{t.liveSimulation}</div>
        <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:20,marginTop:10}}>
          {[[t.monthlyIncome,income,setIncome,10000,80000,T.teal],[t.monthlyExpenses,expense,setExpense,5000,70000,T.gold]].map(([lbl,val,set,min,max,col])=>(
            <div key={lbl}><div style={{display:"flex",justifyContent:"space-between",fontSize:12,color:T.muted,marginBottom:4}}><span>{lbl}</span><span style={{color:col,fontFamily:"monospace"}}>₹{(val/1000).toFixed(0)}k</span></div><input type="range" min={min} max={max} step={1000} value={val} onChange={e=>set(+e.target.value)} style={{width:"100%",accentColor:col}}/></div>
          ))}
        </div>
      </div>
      <div style={{...card,marginBottom:12}}>
        <div style={label}>{t.repaymentHistory}</div>
        <div style={{display:"flex",gap:5,marginTop:8,flexWrap:"wrap"}}>
          {[1,1,1,0,1,1,0,0,1,1,1,1].map((v,i)=><div key={i} style={{width:30,height:30,borderRadius:5,background:v?T.teal+"33":T.red+"33",border:`1px solid ${v?T.teal:T.red}`,display:"flex",alignItems:"center",justifyContent:"center",fontSize:13}}>{v?"✓":"✗"}</div>)}
          <div style={{marginLeft:10,alignSelf:"center",fontSize:11,color:T.muted}}>9/12</div>
        </div>
      </div>
      <div style={{...cardAlt,borderLeft:`3px solid ${T.gold}`}}>
        <div style={label}>{t.aiAdvisor}</div>
        <div style={{display:"flex",gap:8,marginTop:10,flexWrap:"wrap"}}>
          {t.aiQuestions.map(q=><button key={q} onClick={()=>askAI(q)} style={{background:T.dim,border:`1px solid ${T.border}`,borderRadius:20,padding:"5px 12px",fontSize:11,color:T.text,cursor:"pointer"}}>{q}</button>)}
        </div>
        {aiLoading&&<div style={{marginTop:10,fontSize:12,color:T.gold}}>◌ Analysing…</div>}
        {aiResponse&&!aiLoading&&<div style={{marginTop:10,padding:12,background:T.dim,borderRadius:8,fontSize:13,lineHeight:1.7}}>{aiResponse}</div>}
      </div>
    </div>
  );

  const Credit=()=>(
    <div style={sec}><div style={g2}>
      <div style={card}><div style={label}>{t.shapTitle}</div><div style={{marginTop:14}}><div style={{display:"flex",justifyContent:"space-between",fontSize:10,color:T.muted,marginBottom:10}}><span>{t.hurts}</span><span>{t.helps}</span></div>{SHAP_FEATURES.map(f=><ShapBar key={f.name} {...f}/>)}</div><div style={{marginTop:12,paddingTop:10,borderTop:`1px solid ${T.border}`,fontSize:11,color:T.muted}}>Model: XGBoost · Explainability: SHAP · Fairness: Fairlearn</div></div>
      <div><div style={{...card,marginBottom:12}}><div style={label}>{t.fairnessTitle}</div>{[{group:"Gig workers",score:671},{group:"Salaried",score:710},{group:"Rural borrowers",score:648},{group:"Women borrowers",score:680}].map(g=><div key={g.group} style={{display:"flex",alignItems:"center",justifyContent:"space-between",marginBottom:8}}><span style={{fontSize:12}}>{g.group}</span><div style={{display:"flex",alignItems:"center",gap:8}}><div style={{width:90,height:6,borderRadius:3,background:T.border,overflow:"hidden"}}><div style={{width:`${(g.score-300)/6}%`,height:"100%",background:g.score>680?T.teal:g.score>650?T.gold:T.red,borderRadius:3}}/></div><span style={{fontSize:11,fontFamily:"monospace",color:T.muted,width:32}}>{g.score}</span></div></div>)}</div>
      <div style={card}><div style={label}>{t.dataInputs}</div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,marginTop:8}}>{[["Source","Gig Worker"],["Volatility","31%"],["Savings","₹48k"],["Loans","1"],["Exp Ratio",`${((expense/income)*100).toFixed(0)}%`],["Repayment","75%"]].map(([k,v])=><div key={k} style={{background:T.dim,borderRadius:6,padding:"7px 10px"}}><div style={{fontSize:10,color:T.muted}}>{k}</div><div style={{fontSize:13,fontWeight:600,fontFamily:"monospace",color:T.text,marginTop:1}}>{v}</div></div>)}</div></div></div>
    </div></div>
  );

  const Risk=()=>(
    <div style={sec}><div style={g2}>
      <div style={card}><div style={label}>{t.riskTrend}</div><div style={{marginTop:10}}>{RISK_HISTORY.map((d,i)=><div key={i} style={{display:"flex",alignItems:"center",gap:8,marginBottom:5}}><span style={{fontSize:9,color:T.muted,width:24}}>{d.month}</span><div style={{flex:1,height:8,background:T.border,borderRadius:4,overflow:"hidden"}}><div style={{width:`${(d.risk/50)*100}%`,height:"100%",background:d.risk>40?T.red:d.risk>28?T.gold:T.teal,borderRadius:4}}/></div><span style={{fontSize:10,fontFamily:"monospace",color:d.risk>40?T.red:T.muted,width:26,textAlign:"right"}}>{d.risk}%</span></div>)}</div><div style={{marginTop:10,padding:"7px 10px",background:T.dim,borderRadius:6,fontSize:11,color:T.muted}}><span style={{color:T.gold}}>⚠ Threshold: 40%</span></div></div>
      <div><div style={{...card,marginBottom:12}}><div style={label}>{t.riskDrivers}</div>{[{d:"Income drop (Aug–Sep)",s:"high"},{d:"High expense-to-income",s:"medium"},{d:"Irregular repayments",s:"medium"},{d:"Low savings buffer",s:"high"}].map(r=><div key={r.d} style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:8}}><span style={{fontSize:12}}>{r.d}</span><span style={{...badge,background:r.s==="high"?T.red+"22":T.gold+"22",color:r.s==="high"?T.red:T.gold}}>{r.s}</span></div>)}</div>
      <div style={card}><div style={label}>{t.nextMonth}</div><div style={{textAlign:"center",padding:"14px 0"}}><div style={{fontSize:38,fontWeight:700,fontFamily:"monospace",color:T.red}}>38%</div><div style={{fontSize:12,color:T.muted,marginTop:4}}>{t.distressProb}</div><button onClick={()=>askAI("My next-month financial risk is predicted at 38%. Give me a specific action plan.")} style={{marginTop:12,background:T.red+"22",border:`1px solid ${T.red}`,borderRadius:20,padding:"6px 16px",color:T.red,fontSize:11,cursor:"pointer"}}>{t.getActionPlan}</button></div></div></div>
    </div><AIBox accentColor={T.red}/></div>
  );

  const Products=()=>(
    <div style={sec}><div style={{marginBottom:12,fontSize:12,color:T.muted}}>{t.products_title} · Score {score} · Risk {riskPct}%</div>
    <div style={g2}>{PRODUCTS.map(p=><div key={p.id} style={{...card,borderLeft:`3px solid ${p.color}`}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:8}}><div><div style={{fontSize:10,color:T.muted,textTransform:"uppercase",letterSpacing:1}}>{p.type}</div><div style={{fontSize:15,fontWeight:600,marginTop:1}}>{p.name}</div></div><span style={{...badge,background:p.color+"22",color:p.color}}>{p.tag}</span></div><div style={{fontSize:11,color:T.muted,marginBottom:12}}>{p.desc}</div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:6,marginBottom:12}}>{[["Amount",p.amount],["Rate",p.rate],["Term",p.term]].map(([k,v])=><div key={k} style={{background:T.dim,borderRadius:5,padding:"5px 8px"}}><div style={{fontSize:9,color:T.muted}}>{k}</div><div style={{fontSize:11,fontWeight:600,fontFamily:"monospace",color:T.text}}>{v}</div></div>)}</div><div style={{marginBottom:8}}><div style={{display:"flex",justifyContent:"space-between",fontSize:10,color:T.muted,marginBottom:3}}><span>{t.eligibility}</span><span style={{color:p.color,fontFamily:"monospace"}}>{p.eligibility}%</span></div><div style={{height:4,background:T.border,borderRadius:2,overflow:"hidden"}}><div style={{width:`${p.eligibility}%`,height:"100%",background:p.color,borderRadius:2}}/></div></div><button onClick={()=>askAI(`Should I apply for ${p.name}? My credit score is ${score} and income is ₹${income}.`)} style={{width:"100%",background:p.color+"11",border:`1px solid ${p.color}33`,borderRadius:6,padding:"7px",color:p.color,fontSize:11,cursor:"pointer"}}>{t.explainElig}</button></div>)}</div>
    <AIBox accentColor={T.gold}/></div>
  );

  const RLAgent=()=>(
    <div style={sec}><div style={g2}>
      <div style={card}><div style={label}>{t.rlTitle}</div><div style={{marginTop:12}}>{RL_EPS.map((ep,i)=><div key={i} style={{display:"flex",alignItems:"center",gap:10,marginBottom:7,fontSize:12}}><span style={{color:T.muted,fontSize:10,width:24}}>E{ep.ep}</span><span style={{...badge,background:ep.reward===1?T.teal+"22":ep.reward===-1?T.red+"22":T.gold+"22",color:ep.reward===1?T.teal:ep.reward===-1?T.red:T.gold}}>{ep.action}</span><span style={{fontSize:10,color:T.muted}}>R:{ep.reward>0?"+":""}{ep.reward}</span><span style={{marginLeft:"auto",fontFamily:"monospace",fontSize:11}}>{ep.score}</span></div>)}</div><div style={{display:"flex",gap:14,marginTop:10,fontSize:10,color:T.muted}}><span><span style={{color:T.teal}}>●</span> On-time (+1)</span><span><span style={{color:T.gold}}>●</span> Partial (+0.5)</span><span><span style={{color:T.red}}>●</span> Missed (−1)</span></div></div>
      <div><div style={{...card,marginBottom:12}}><div style={label}>{t.stateSpace}</div>{[["Income",`₹${(income/1000).toFixed(0)}k`,T.teal],["Debt","₹5.8k",T.gold],["Savings","₹48k",T.blue],["Risk",`${riskPct}%`,T.red],["Score",`${score}`,T.purple]].map(([k,v,c])=><div key={k} style={{display:"flex",justifyContent:"space-between",marginBottom:7,padding:"5px 10px",background:T.dim,borderRadius:5}}><span style={{fontSize:12}}>{k}</span><span style={{fontSize:12,fontFamily:"monospace",color:c}}>{v}</span></div>)}</div>
      <div style={card}><div style={label}>{t.rewardFn}</div><div style={{padding:"10px 12px",background:T.dim,borderRadius:7,fontFamily:"monospace",fontSize:11,lineHeight:1.9}}><div><span style={{color:T.teal}}>+1.0</span> On-time repayment</div><div><span style={{color:T.gold}}>+0.5</span> Partial payment</div><div><span style={{color:T.red}}>−1.0</span> Missed payment</div><div><span style={{color:T.purple}}>+0.2</span> Score ≥ +10pts</div></div></div></div>
    </div></div>
  );

  const FINNs=()=>(
    <div style={sec}><div style={g2}>
      <div style={card}><div style={label}>{t.finnsTitle}</div><div style={{fontSize:11,color:T.muted,marginBottom:12}}>Hard economic rules baked into the model loss function.</div>{FINN_C.map((c,i)=><div key={i} style={{display:"flex",alignItems:"center",justifyContent:"space-between",marginBottom:8,padding:"9px 12px",background:c.status==="warn"?T.gold+"0d":T.dim,border:`1px solid ${c.status==="warn"?T.gold+"44":T.border}`,borderRadius:7}}><div style={{flex:1}}><div style={{fontSize:12}}>{c.rule}</div><div style={{fontSize:10,color:T.muted,marginTop:1}}>Actual: <span style={{fontFamily:"monospace",color:c.status==="warn"?T.gold:T.text}}>{c.actual}</span> · {c.threshold}</div></div><span style={{...badge,marginLeft:10,background:c.status==="warn"?T.gold+"22":T.teal+"22",color:c.status==="warn"?T.gold:T.teal}}>{c.status}</span></div>)}</div>
      <div><div style={{...card,marginBottom:12}}><div style={label}>{t.finnVsML}</div>{[{label:"Respects financial axioms",finn:true,ml:false},{label:"Zero-income → zero credit",finn:true,ml:false},{label:"Debt cap enforcement",finn:true,ml:false},{label:"Learns from data",finn:true,ml:true},{label:"Handles rare edge cases",finn:true,ml:false}].map(r=><div key={r.label} style={{display:"flex",alignItems:"center",justifyContent:"space-between",marginBottom:7,padding:"5px 10px",background:T.dim,borderRadius:5}}><span style={{fontSize:12,flex:1}}>{r.label}</span><span style={{fontSize:11,color:r.finn?T.teal:T.red,fontFamily:"monospace",minWidth:50,textAlign:"center"}}>{r.finn?"✓ FINN":"✗ FINN"}</span><span style={{fontSize:11,color:r.ml?T.teal:T.red,fontFamily:"monospace",minWidth:38,textAlign:"center"}}>{r.ml?"✓ ML":"✗ ML"}</span></div>)}</div>
      <div style={card}><div style={label}>{t.lossComponents}</div><div style={{padding:"10px 12px",background:T.dim,borderRadius:7,fontFamily:"monospace",fontSize:11,lineHeight:2}}><div><span style={{color:T.gold}}>L_total</span> = L_data</div><div style={{paddingLeft:12}}>+ <span style={{color:T.red}}>λ₁</span>·L_exp_cap</div><div style={{paddingLeft:12}}>+ <span style={{color:T.red}}>λ₂</span>·L_dti_ratio</div><div style={{paddingLeft:12}}>+ <span style={{color:T.red}}>λ₃</span>·L_zero_income</div><div style={{paddingLeft:12}}>+ <span style={{color:T.red}}>λ₄</span>·L_repay_floor</div></div><button onClick={()=>askAI("What are Finance-Informed Neural Networks and why are economic constraints important in financial ML?")} style={{marginTop:10,width:"100%",background:T.gold+"11",border:`1px solid ${T.gold}33`,borderRadius:6,padding:"7px",color:T.gold,fontSize:11,cursor:"pointer"}}>{t.explainFinn}</button></div></div>
    </div><AIBox accentColor={T.gold}/></div>
  );

  // ── BANK TABS ─────────────────────────────────────────────────────────────
  const BankOverview=()=>(
    <div style={sec}>
      <div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:12,marginBottom:12}}>
        {[[t.totalApplicants,"2,847",T.blue,"↑ 12% this month"],[t.activeLoans,"1,203",T.teal,"₹18.4 Cr disbursed"],[t.avgScore,"664",T.gold,"Industry avg: 650"],[t.portfolioRisk,"31%",T.red,"⚠ 8% high-risk"]].map(([lbl,val,col,sub])=><div key={lbl} style={card}><div style={label}>{lbl}</div><div style={{fontSize:20,fontWeight:700,fontFamily:"monospace",color:col,marginBottom:3}}>{val}</div><div style={{fontSize:11,color:T.muted}}>{sub}</div></div>)}
      </div>
      <div style={{...card,marginBottom:12}}>
        <div style={label}>Portfolio Risk Distribution</div>
        <div style={{display:"flex",gap:2,height:20,borderRadius:4,overflow:"hidden",marginTop:10}}>
          {[{pct:42,c:T.teal,l:"Low"},{pct:35,c:T.gold,l:"Med"},{pct:15,c:"#f97316",l:"High"},{pct:8,c:T.red,l:"Crit"}].map(s=><div key={s.l} style={{width:`${s.pct}%`,background:s.c,display:"flex",alignItems:"center",justifyContent:"center",fontSize:10,color:"#07090f",fontWeight:700}}>{s.pct>10?s.pct+"%":""}</div>)}
        </div>
        <div style={{display:"flex",gap:14,marginTop:8,fontSize:10,color:T.muted}}>
          {[{c:T.teal,l:"Low (42%)"},{c:T.gold,l:"Medium (35%)"},{c:"#f97316",l:"High (15%)"},{c:T.red,l:"Critical (8%)"}].map(s=><span key={s.l}><span style={{color:s.c}}>●</span> {s.l}</span>)}
        </div>
      </div>
      <div style={card}><div style={label}>Recent Activity</div><div style={{marginTop:8}}>{applicants.slice(0,4).map(a=><div key={a.id} style={{display:"flex",alignItems:"center",gap:12,padding:"8px 0",borderBottom:`1px solid ${T.border}`}}><span style={{fontSize:10,color:T.muted,fontFamily:"monospace",width:44}}>{a.id}</span><span style={{fontSize:13,flex:1}}>{a.name}</span><span style={{fontSize:12,fontFamily:"monospace",color:a.score>700?T.teal:a.score>640?T.gold:T.red,fontWeight:600}}>{a.score}</span><span style={{...badge,background:a.status==="approved"?T.teal+"22":a.status==="flagged"?T.red+"22":T.dim,color:a.status==="approved"?T.teal:a.status==="flagged"?T.red:T.muted}}>{a.status}</span></div>)}</div></div>
    </div>
  );

  const BankApplicants=()=>(
    <div style={sec}>
      <div style={{...card,marginBottom:12}}>
        <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:14}}><div style={label}>{t.applicantList}</div><button onClick={()=>askAI("As a bank officer, how should I fairly evaluate a gig worker's loan application using AI scoring?")} style={{background:T.blue+"22",border:`1px solid ${T.blue}33`,borderRadius:20,padding:"5px 14px",color:T.blue,fontSize:11,cursor:"pointer"}}>AI Evaluation Guide ↗</button></div>
        {applicants.map(a=><div key={a.id} style={{padding:"12px 14px",marginBottom:8,background:a.status==="flagged"?T.red+"08":a.status==="approved"?T.teal+"08":T.dim,border:`1px solid ${a.status==="flagged"?T.red+"33":a.status==="approved"?T.teal+"33":T.border}`,borderRadius:8}}>
          <div style={{display:"flex",alignItems:"center",gap:10,flexWrap:"wrap"}}>
            <span style={{fontSize:10,color:T.muted,fontFamily:"monospace",width:44}}>{a.id}</span>
            <span style={{fontSize:14,fontWeight:600,flex:1,minWidth:110}}>{a.name}</span>
            <span style={{fontSize:11,color:T.muted}}>{a.source}</span>
            <span style={{fontSize:13,fontFamily:"monospace",color:a.score>700?T.teal:a.score>640?T.gold:T.red,fontWeight:600}}>{a.score}</span>
            <span style={{fontSize:11,color:a.risk>40?T.red:T.muted}}>Risk:{a.risk}%</span>
            <span style={{fontSize:11,color:T.muted}}>{a.product}</span>
            {a.status==="pending"&&<>
              <button onClick={()=>setApplicants(p=>p.map(x=>x.id===a.id?{...x,status:"approved"}:x))} style={{background:T.teal+"22",border:`1px solid ${T.teal}44`,borderRadius:5,padding:"4px 10px",color:T.teal,fontSize:11,cursor:"pointer"}}>{t.approveBtn}</button>
              <button onClick={()=>setApplicants(p=>p.map(x=>x.id===a.id?{...x,status:"flagged"}:x))} style={{background:T.gold+"22",border:`1px solid ${T.gold}44`,borderRadius:5,padding:"4px 10px",color:T.gold,fontSize:11,cursor:"pointer"}}>{t.flagBtn}</button>
              <button onClick={()=>setApplicants(p=>p.map(x=>x.id===a.id?{...x,status:"rejected"}:x))} style={{background:T.red+"22",border:`1px solid ${T.red}44`,borderRadius:5,padding:"4px 10px",color:T.red,fontSize:11,cursor:"pointer"}}>{t.rejectBtn}</button>
            </>}
            {a.status!=="pending"&&<span style={{...badge,background:a.status==="approved"?T.teal+"22":a.status==="rejected"?T.red+"22":T.gold+"22",color:a.status==="approved"?T.teal:a.status==="rejected"?T.red:T.gold}}>{a.status}</span>}
          </div>
        </div>)}
      </div>
      <AIBox accentColor={T.blue}/>
    </div>
  );

  const BankPortfolio=()=>(
    <div style={sec}><div style={g2}>
      <div style={card}><div style={label}>Sector Breakdown</div>{[{sector:"Agriculture & Rural",amt:"₹4.2 Cr",pct:23,risk:28,color:T.teal},{sector:"Gig & Informal",amt:"₹3.8 Cr",pct:21,risk:44,color:T.gold},{sector:"Micro Enterprise",amt:"₹5.1 Cr",pct:28,risk:31,color:T.blue},{sector:"Salaried / Formal",amt:"₹5.3 Cr",pct:28,risk:14,color:T.purple}].map(s=><div key={s.sector} style={{marginBottom:12}}><div style={{display:"flex",justifyContent:"space-between",fontSize:12,marginBottom:4}}><span>{s.sector}</span><span style={{fontFamily:"monospace",color:T.muted}}>{s.amt}</span></div><div style={{display:"flex",alignItems:"center",gap:8}}><div style={{flex:1,height:8,background:T.border,borderRadius:4,overflow:"hidden"}}><div style={{width:`${s.pct*3.5}%`,height:"100%",background:s.color,borderRadius:4}}/></div><span style={{fontSize:10,color:s.risk>40?T.red:T.muted,minWidth:50,textAlign:"right"}}>Risk:{s.risk}%</span></div></div>)}</div>
      <div style={card}><div style={label}>Federated Learning Status</div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,marginTop:10}}>{[{bank:"SBI Branch",status:"synced",rounds:142,color:T.teal},{bank:"PNB Branch",status:"synced",rounds:138,color:T.teal},{bank:"BoB Branch",status:"training",rounds:135,color:T.gold},{bank:"UCO Bank",status:"pending",rounds:112,color:T.muted}].map(b=><div key={b.bank} style={{background:T.dim,borderRadius:8,padding:"10px 12px"}}><div style={{fontSize:11,fontWeight:600,marginBottom:4}}>{b.bank}</div><span style={{...badge,background:b.color+"22",color:b.color}}>{b.status}</span><div style={{fontSize:10,color:T.muted,marginTop:4}}>Rounds:{b.rounds}</div></div>)}</div><div style={{marginTop:10,fontSize:11,color:T.muted}}>Global accuracy: <span style={{color:T.teal,fontFamily:"monospace"}}>87.3%</span> · No raw data shared</div></div>
    </div></div>
  );

  const BankFairness=()=>(
    <div style={sec}><div style={g2}>
      <div style={card}><div style={label}>{t.fairnessAudit}</div>{[{group:"Gig workers",approved:62,avg_score:671,disparity:"+3%"},{group:"Agricultural workers",approved:54,avg_score:638,disparity:"-8%"},{group:"Women borrowers",approved:67,avg_score:680,disparity:"+7%"},{group:"Rural borrowers",approved:49,avg_score:642,disparity:"-12%"},{group:"SC/ST borrowers",approved:51,avg_score:645,disparity:"-10%"},{group:"Youth (18–25)",approved:58,avg_score:612,disparity:"-3%"}].map(g=><div key={g.group} style={{marginBottom:10,padding:"8px 12px",background:T.dim,borderRadius:7}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:5}}><span style={{fontSize:12,fontWeight:600}}>{g.group}</span><span style={{fontSize:11,fontFamily:"monospace",color:g.disparity.startsWith("-")?T.red:T.teal}}>{g.disparity} vs baseline</span></div><div style={{display:"flex",gap:12,fontSize:11,color:T.muted,marginBottom:5}}><span>Approval:<span style={{fontFamily:"monospace",color:T.text,marginLeft:3}}>{g.approved}%</span></span><span>Avg score:<span style={{fontFamily:"monospace",color:T.text,marginLeft:3}}>{g.avg_score}</span></span></div><div style={{height:4,background:T.border,borderRadius:2,overflow:"hidden"}}><div style={{width:`${g.approved}%`,height:"100%",background:g.approved>60?T.teal:g.approved>52?T.gold:T.red,borderRadius:2}}/></div></div>)}</div>
      <div><div style={{...card,marginBottom:12}}><div style={label}>Bias Mitigation Applied</div>{[{tech:"Reweighting (pre-processing)",active:true},{tech:"Equalized odds constraint",active:true},{tech:"Calibrated equal opportunity",active:true},{tech:"Demographic parity check",active:false},{tech:"Counterfactual fairness",active:false}].map(m=><div key={m.tech} style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:8,fontSize:12}}><span>{m.tech}</span><span style={{...badge,background:m.active?T.teal+"22":T.border,color:m.active?T.teal:T.muted}}>{m.active?"active":"off"}</span></div>)}</div>
      <div style={card}><div style={label}>Regulatory Compliance</div>{[["RBI Fair Practices Code","✓ Compliant",T.teal],["Equal Credit Opportunity","✓ Compliant",T.teal],["DPDP Act 2023","✓ Compliant",T.teal],["Algorithmic Transparency","⚠ Partial",T.gold]].map(([k,v,c])=><div key={k} style={{display:"flex",justifyContent:"space-between",marginBottom:7,fontSize:12}}><span style={{color:T.muted}}>{k}</span><span style={{color:c,fontWeight:600}}>{v}</span></div>)}</div></div>
    </div></div>
  );

  const BankWorkflow=()=>(
    <div style={sec}><div style={g2}>
      <div style={card}><div style={label}>{t.approvalWorkflow}</div><div style={{marginTop:10}}>{[{stage:"AI Scoring",count:2847,color:T.blue,done:true},{stage:"Risk Check",count:2847,color:T.blue,done:true},{stage:"FINN Constraint Validation",count:2847,color:T.blue,done:true},{stage:"Officer Review",count:312,color:T.gold,done:false},{stage:"Final Approval",count:198,color:T.teal,done:false},{stage:"Disbursed",count:1203,color:T.teal,done:true}].map((s,i)=><div key={i} style={{display:"flex",alignItems:"center",gap:12,marginBottom:10}}><div style={{width:32,height:32,borderRadius:"50%",background:s.done?s.color+"33":T.dim,border:`1px solid ${s.done?s.color:T.border}`,display:"flex",alignItems:"center",justifyContent:"center",fontSize:12,color:s.done?s.color:T.muted,fontWeight:600,flexShrink:0}}>{i+1}</div><div style={{flex:1}}><div style={{fontSize:12,fontWeight:600}}>{s.stage}</div><div style={{fontSize:10,color:T.muted}}>{s.count.toLocaleString()} applications</div></div><span style={{...badge,background:s.done?s.color+"22":T.dim,color:s.done?s.color:T.muted}}>{s.done?"done":"pending"}</span></div>)}</div></div>
      <div><div style={{...card,marginBottom:12}}><div style={label}>{t.batchUpload}</div><div style={{marginTop:12,padding:20,border:`2px dashed ${T.border}`,borderRadius:8,textAlign:"center"}}><div style={{fontSize:24,marginBottom:8}}>📄</div><div style={{fontSize:13,color:T.muted,marginBottom:10}}>Drop CSV with applicant data</div><div style={{fontSize:11,color:T.muted,marginBottom:14}}>Columns: income, expenses, repayment_history, loans</div><button style={{background:T.blue+"22",border:`1px solid ${T.blue}`,borderRadius:6,padding:"8px 20px",color:T.blue,fontSize:12,cursor:"pointer"}}>Upload & Score Batch ↗</button></div><div style={{marginTop:10,fontSize:11,color:T.muted}}>Last batch: 847 applicants · 3 mins · Accuracy: 91.2%</div></div>
      <div style={card}><div style={label}>Audit Trail</div>{[{time:"09:42",officer:"Priya K.",action:"Approved AP004"},{time:"09:31",officer:"Rajan M.",action:"Flagged AP002"},{time:"09:15",officer:"System",action:"Batch scored 312"},{time:"08:50",officer:"Priya K.",action:"Approved AP007"}].map((e,i)=><div key={i} style={{display:"flex",gap:10,marginBottom:7,padding:"5px 0",borderBottom:`1px solid ${T.border}`}}><span style={{fontSize:10,color:T.muted,fontFamily:"monospace",width:36}}>{e.time}</span><span style={{fontSize:11,flex:1}}>{e.action}</span><span style={{fontSize:10,color:T.muted}}>{e.officer}</span></div>)}</div></div>
    </div></div>
  );

  const renderUser=()=>({dashboard:<Dashboard/>,credit:<Credit/>,risk:<Risk/>,products:<Products/>,rl:<RLAgent/>,finn:<FINNs/>}[tab]||<Dashboard/>);
  const renderBank=()=>({overview:<BankOverview/>,applicants:<BankApplicants/>,portfolio:<BankPortfolio/>,fairness:<BankFairness/>,workflow:<BankWorkflow/>}[bankTab]||<BankOverview/>);

  return (
    <div style={{minHeight:"100vh",background:T.bg,fontFamily:"'DM Sans',system-ui,sans-serif",color:T.text}}>
      <style>{`@import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;600;700&display=swap');*{box-sizing:border-box;margin:0;padding:0;}input[type=range]{height:4px;cursor:pointer;}button{font-family:inherit;}`}</style>
      {/* HEADER */}
      <div style={{background:T.card,borderBottom:`1px solid ${T.border}`,padding:"0 20px",display:"flex",alignItems:"center",gap:12,height:50,flexWrap:"wrap"}}>
        <div style={{fontSize:13,fontWeight:700,color:role==="bank"?T.blue:T.gold,fontFamily:"monospace",letterSpacing:1}}>◈ {t.appName}</div>
        <div style={{width:1,height:18,background:T.border}}/>
        <span style={{fontSize:10,padding:"3px 10px",borderRadius:20,background:role==="bank"?T.blue+"22":T.gold+"22",color:role==="bank"?T.blue:T.gold,fontWeight:600}}>{role==="bank"?t.role_bank:t.role_user}</span>
        <button onClick={()=>setRole(r=>r==="user"?"bank":"user")} style={{background:role==="bank"?T.blue+"22":T.gold+"22",border:`1px solid ${role==="bank"?T.blue:T.gold}44`,borderRadius:20,padding:"4px 12px",color:role==="bank"?T.blue:T.gold,fontSize:11,cursor:"pointer"}}>{role==="user"?t.switchToBank:t.switchToUser}</button>
        <div style={{flex:1}}/>
        <nav style={{display:"flex",gap:2,flexWrap:"wrap"}}>
          {role==="user"?Object.entries(t.tabs).map(([id,lbl])=><button key={id} style={navBtn(tab===id)} onClick={()=>{setTab(id);setAiResponse("");}}>{lbl}</button>):Object.entries(t.bankTabs).map(([id,lbl])=><button key={id} style={navBtn(bankTab===id)} onClick={()=>setBankTab(id)}>{lbl}</button>)}
        </nav>
        <div style={{position:"relative"}}>
          <button onClick={()=>setShowLang(m=>!m)} style={{background:T.dim,border:`1px solid ${T.border}`,borderRadius:6,padding:"4px 10px",color:T.text,fontSize:11,cursor:"pointer"}}>{LANGS.find(l=>l.code===lang)?.label} ▾</button>
          {showLang&&<div style={{position:"absolute",right:0,top:32,background:T.card,border:`1px solid ${T.border}`,borderRadius:8,zIndex:100,minWidth:130,overflow:"hidden"}}>
            {LANGS.map(l=><button key={l.code} onClick={()=>{setLang(l.code);setShowLang(false);}} style={{display:"block",width:"100%",textAlign:"left",padding:"8px 14px",background:lang===l.code?T.dim:"transparent",border:"none",color:lang===l.code?T.text:T.muted,fontSize:12,cursor:"pointer"}}><span style={{marginRight:8,fontWeight:700}}>{l.label}</span>{l.name}</button>)}
          </div>}
        </div>
        <div style={{display:"flex",alignItems:"center",gap:5}}><span style={{width:6,height:6,borderRadius:"50%",background:T.teal,display:"inline-block"}}/><span style={{fontSize:10,color:T.muted}}>{t.live}</span></div>
      </div>
      {role==="user"?renderUser():renderBank()}
    </div>
  );
}
